{
  LOG.error("Got exception in the channel !",cause);
  closeOnError(ctx,cause);
}
