{
  try {
    getResultSet("exception.json");
    Assert.fail("Execute should have thrown an exception");
  }
 catch (  PinotClientException e) {
  }
}
